// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJMnNXXhz8Asu1XcGejs6uFh3KHF9CUz0',
    appId: '1:230612495673:web:c1f5bd57fa834da66c0ce8',
    messagingSenderId: '230612495673',
    projectId: 'gsbfund',
    authDomain: 'gsbfund.firebaseapp.com',
    storageBucket: 'gsbfund.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcEuos_dmasHLLt2bwSRKMpdQoYWrruIE',
    appId: '1:230612495673:android:97ab031c8e8bcfa16c0ce8',
    messagingSenderId: '230612495673',
    projectId: 'gsbfund',
    storageBucket: 'gsbfund.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCidIWwNIIZFh8xq8VETJCYKhFh9xnEpq4',
    appId: '1:230612495673:ios:e297ad8c23d5166f6c0ce8',
    messagingSenderId: '230612495673',
    projectId: 'gsbfund',
    storageBucket: 'gsbfund.appspot.com',
    iosClientId: '230612495673-iif7rpcgs51mrt155qb4gdbg8vdjcgff.apps.googleusercontent.com',
    iosBundleId: 'com.dreamapp.glamshinebufferfund',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCidIWwNIIZFh8xq8VETJCYKhFh9xnEpq4',
    appId: '1:230612495673:ios:e297ad8c23d5166f6c0ce8',
    messagingSenderId: '230612495673',
    projectId: 'gsbfund',
    storageBucket: 'gsbfund.appspot.com',
    iosClientId: '230612495673-iif7rpcgs51mrt155qb4gdbg8vdjcgff.apps.googleusercontent.com',
    iosBundleId: 'com.dreamapp.glamshinebufferfund',
  );
}
