
name: Deploying Website To Firebase | Dream-25
on: push
jobs:
    hosting:
      name: Deploy Website | Dream-25
      runs-on: ubuntu-latest
      steps:
        # Checkout Repository
        - uses: actions/checkout@v1

        # Install Flutter command
        - uses: subosito/flutter-action@v2
          with:
            channel: 'stable'

        # Build Website
        - name: Build Website | Dream-25
          run: |
            flutter --version
            flutter config --enable-web
            flutter pub get
            flutter build web --web-renderer html --release
          working-directory: ./

        # Deploy Firebase Hosting
        - name: Deploy Firebase Hosting | Dream-25
          uses: w9jds/firebase-action@master
          with:
            args: deploy --only hosting:dream-softwares
          env:
            FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
            PROJECT_PATH: ./