name: Deploying Website To Firebase | Dream-25
on: push
jobs:
    hosting:
      name: Deploy Website | Dream-25
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - uses: subosito/flutter-action@v2
          with:
            flutter-version: '3.0.1'
            channel: 'stable'
        - run: flutter --version
        # Build Website
        - name: Build Website | Dream-25
          run: |
            flutter config --enable-web
            flutter pub get
            flutter build web --web-renderer canvaskit --release 
          working-directory: ./

        # Deploy Firebase Hosting
        - name: Deploy Firebase Hosting | Dream-25
          uses: w9jds/firebase-action@master
          with:
            args: deploy --only hosting:gsbfund
          env:
            FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
            PROJECT_PATH: ./